### ISSUE TITLE
Updated code

### ISSUE THREAD

**Issue by Podugusowjan** [Datta4486/Hand-Cricket#1]
Title
import random
print("Welcome to my second attempt at creating a barely functioning game in Python.\n This time it is Hand-Cricket... well you aren't really using ur hands to play this game so it's just RNG Cricket.\n Would you like to hear the rules first? \n Type 'Yes' or 'No'...")
typocheck = 0
Rules = str(input(""))
playerside = ""
botside = ""
inning_end = 0
playerscore = 0
botscore = 0
wicket = 0

# Rules
while typocheck != 1: #Check for any typos when typing strings
    if Rules.lower() == "yes":
        print("The game is played with numbers starting from 1-10.\n The batter must type a value between 1-10 and hope that the bowler didn't type the same otherwise they are out! It first starts with a toss and the victor chooses wether to bat or bowl.\n The bowler tries to defeat the batter by predicting the number he is about to type. For every ball, the number typed by the batter would be added to the total score.\n User with highest score wins!")
        typocheck = 1
    elif Rules.lower() != "no":
        print("Invalid Choice, try again")
    else:
      typocheck = 1
typocheck = 0

# Confirmation to play the game
print("Would you like to play a game?\nAs usual type 'Yes' or 'No'...")
choice = str(input(""))
if choice.lower() == "yes":
    bottoss = ""
    # Coin Flip
    print("Well, time to toss. Heads or Tails?")
    typocheck = 0
    while typocheck != 1: #TypoCheck Again
        coinflip = str(input(""))
        if coinflip.lower() == "heads":
            bottoss = "tails"
            typocheck = 1
        elif coinflip.lower() == "tails":
            bottoss = "heads"
            typocheck = 1
        else:
            print("Invalid Choice, try again!")
            typecheck = 0
    tosswin = random.choice(["heads","tails"])
    #  Toss Winner Declaration
    if coinflip == tosswin:
        print("Yay, you won the toss, you can choose either batting or bowling.\nPress 1 to bat or press 2 to bowl")
        playerside = int(input(""))
    elif coinflip != tosswin:
    	botside = random.choice(["bat","bowl"])
    	print("You lost the toss, the bot decided to ",botside)
    	playerside = 2
    while inning_end != 1:
    	if playerside == 1:
    		while wicket != 1:
    			botball = random.randrange(1,11,1)
    			playerball = int(input("Enter the number"))
    			if playerball != botball:
    			    print("You hit",playerball, "while the bot bowled",botball)
    			    playerscore += playerball
    			    print("Score is:",playerscore)
    			elif playerball == botball:
    			    print("Wicket!, your total score is ",playerscore)
    			    wicket = 1
    			    playerside = 2
    	elif playerside == 2:
    		wicket = 0
    		while wicket != 1:
    				botball = random.randrange(1,11,1)
    				playerball = int(input("Enter the number"))
    				if playerball != botball:
    				   	print("You bowled",playerball, "while the bot hit",botball)
    			   		botscore += botball
    			   		print("Score is:",botscore)
    				elif playerball == botball:
    				    	print("Wicket!, bot total score is ",botscore)
    				    	playerside=1
    				    	wicket=1
                            inning_end = 0
    while inning_end != 1:
    	wicket = 0
    	if playerside == 1:
    		while wicket != 1:
    			botball = random.randrange(1,11,1)
    			playerball = int(input("Enter the number"))
    			if playerball != botball:
    			    print("You hit",playerball, "while the bot bowled",botball)
    			    playerscore += playerball
    			    print("Score is:",playerscore)
    			elif playerball == botball:
    			    print("Wicket!, your total score is ",playerscore)
    			    wicket = 1
    	elif playerside == 2:
    		wicket = 0
    		while wicket != 1:
    				botball = random.randrange(1,11,1)
    				playerball = int(input("Enter the number"))
    				if playerball != botball:
    				   	print("You bowled",playerball, "while the bot hit",botball)
    			   		botscore += botball
    			   		print("Score is:",botscore)
    				elif playerball == botball:
    				    	print("Wicket!, bot total score is ",botscore)
    				    	wicket=1

**Comment by Datta4486** [comment]
Done, merged to main branch
